### ISSUE TITLE
IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.

### ISSUE THREAD

**Issue by notefox** [OpenHistoricalDataMap/OHDMOfflineViewer#7]
App crashes after continuously refreshing maps with no connection to the server and switching to  home and back, continue till the app cashes

StackTrace:
        at de.htwBerlin.ois.viewModels.ViewModelMainActivity$1.getHttpResponse(ViewModelMainActivity.java:92)
        at de.htwBerlin.ois.serverCommunication.HttpRequest.onPostExecute(HttpRequest.java:113)
        at de.htwBerlin.ois.serverCommunication.HttpRequest.onPostExecute(HttpRequest.java:15)

**Comment by WilliBoelke** [comment]
Fixed
